<?xml version="1.0" encoding="utf-8"?><Database Name="artshome" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=58.64.149.22;Initial Catalog=artshome;Persist Security Info=True;User ID=artshome" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Table_Admin" Member="Table_Admin">
    <Type Name="Table_Admin">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="productPermission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="collectionPermission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="designerPermission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="superPermission" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_News" Member="Table_News">
    <Type Name="Table_News">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Body" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Info" Member="Table_Info">
    <Type Name="Table_Info">
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContactAddress" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactRole" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactPhone" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactMobie" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ContactSkype" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Product" Member="Table_Product">
    <Type Name="Table_Product">
      <Column Name="code" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="shape" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="imageUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="collection" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Designer" Member="Table_Designer">
    <Type Name="Table_Designer">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="imageUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_Collection" Member="Table_Collection">
    <Type Name="Table_Collection">
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="imageUrl" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="designer" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Table_TradeShow" Member="Table_TradeShow">
    <Type Name="Table_TradeShow">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="link" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="date_end" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="artshome.Table_Bespoke" Member="Table_Bespoke">
    <Type Name="Table_Bespoke">
      <Column Name="imageUrl" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="contentText" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="artshome.Table_Banners" Member="Table_Banners">
    <Type Name="Table_Banners">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pic1Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic2Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic3Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic4Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic5Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic6Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic7Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="pic8Url" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>