#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertTable_Admin(Table_Admin instance);
  partial void UpdateTable_Admin(Table_Admin instance);
  partial void DeleteTable_Admin(Table_Admin instance);
  partial void InsertTable_Collection(Table_Collection instance);
  partial void UpdateTable_Collection(Table_Collection instance);
  partial void DeleteTable_Collection(Table_Collection instance);
  partial void InsertTable_Designer(Table_Designer instance);
  partial void UpdateTable_Designer(Table_Designer instance);
  partial void DeleteTable_Designer(Table_Designer instance);
  partial void InsertTable_Product(Table_Product instance);
  partial void UpdateTable_Product(Table_Product instance);
  partial void DeleteTable_Product(Table_Product instance);
  partial void InsertTable_News(Table_News instance);
  partial void UpdateTable_News(Table_News instance);
  partial void DeleteTable_News(Table_News instance);
  partial void InsertTable_Info(Table_Info instance);
  partial void UpdateTable_Info(Table_Info instance);
  partial void DeleteTable_Info(Table_Info instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Table_Admin> Table_Admin
	{
		get
		{
			return this.GetTable<Table_Admin>();
		}
	}
	
	public System.Data.Linq.Table<Table_Collection> Table_Collection
	{
		get
		{
			return this.GetTable<Table_Collection>();
		}
	}
	
	public System.Data.Linq.Table<Table_Designer> Table_Designer
	{
		get
		{
			return this.GetTable<Table_Designer>();
		}
	}
	
	public System.Data.Linq.Table<Table_Product> Table_Product
	{
		get
		{
			return this.GetTable<Table_Product>();
		}
	}
	
	public System.Data.Linq.Table<Table_News> Table_News
	{
		get
		{
			return this.GetTable<Table_News>();
		}
	}
	
	public System.Data.Linq.Table<Table_Info> Table_Info
	{
		get
		{
			return this.GetTable<Table_Info>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Admin")]
public partial class Table_Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _name;
	
	private string _password;
	
	private int _productPermission;
	
	private int _collectionPermission;
	
	private int _designerPermission;
	
	private int _superPermission;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnproductPermissionChanging(int value);
    partial void OnproductPermissionChanged();
    partial void OncollectionPermissionChanging(int value);
    partial void OncollectionPermissionChanged();
    partial void OndesignerPermissionChanging(int value);
    partial void OndesignerPermissionChanged();
    partial void OnsuperPermissionChanging(int value);
    partial void OnsuperPermissionChanged();
    #endregion
	
	public Table_Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productPermission", DbType="Int NOT NULL")]
	public int productPermission
	{
		get
		{
			return this._productPermission;
		}
		set
		{
			if ((this._productPermission != value))
			{
				this.OnproductPermissionChanging(value);
				this.SendPropertyChanging();
				this._productPermission = value;
				this.SendPropertyChanged("productPermission");
				this.OnproductPermissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collectionPermission", DbType="Int NOT NULL")]
	public int collectionPermission
	{
		get
		{
			return this._collectionPermission;
		}
		set
		{
			if ((this._collectionPermission != value))
			{
				this.OncollectionPermissionChanging(value);
				this.SendPropertyChanging();
				this._collectionPermission = value;
				this.SendPropertyChanged("collectionPermission");
				this.OncollectionPermissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designerPermission", DbType="Int NOT NULL")]
	public int designerPermission
	{
		get
		{
			return this._designerPermission;
		}
		set
		{
			if ((this._designerPermission != value))
			{
				this.OndesignerPermissionChanging(value);
				this.SendPropertyChanging();
				this._designerPermission = value;
				this.SendPropertyChanged("designerPermission");
				this.OndesignerPermissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_superPermission", DbType="Int NOT NULL")]
	public int superPermission
	{
		get
		{
			return this._superPermission;
		}
		set
		{
			if ((this._superPermission != value))
			{
				this.OnsuperPermissionChanging(value);
				this.SendPropertyChanging();
				this._superPermission = value;
				this.SendPropertyChanged("superPermission");
				this.OnsuperPermissionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Collection")]
public partial class Table_Collection : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _name;
	
	private string _description;
	
	private string _imageUrl;
	
	private string _designer;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    partial void OndesignerChanging(string value);
    partial void OndesignerChanged();
    #endregion
	
	public Table_Collection()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string imageUrl
	{
		get
		{
			return this._imageUrl;
		}
		set
		{
			if ((this._imageUrl != value))
			{
				this.OnimageUrlChanging(value);
				this.SendPropertyChanging();
				this._imageUrl = value;
				this.SendPropertyChanged("imageUrl");
				this.OnimageUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string designer
	{
		get
		{
			return this._designer;
		}
		set
		{
			if ((this._designer != value))
			{
				this.OndesignerChanging(value);
				this.SendPropertyChanging();
				this._designer = value;
				this.SendPropertyChanged("designer");
				this.OndesignerChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Designer")]
public partial class Table_Designer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _name;
	
	private string _description;
	
	private string _imageUrl;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    #endregion
	
	public Table_Designer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string imageUrl
	{
		get
		{
			return this._imageUrl;
		}
		set
		{
			if ((this._imageUrl != value))
			{
				this.OnimageUrlChanging(value);
				this.SendPropertyChanging();
				this._imageUrl = value;
				this.SendPropertyChanged("imageUrl");
				this.OnimageUrlChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Product")]
public partial class Table_Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _code;
	
	private string _shape;
	
	private string _size;
	
	private string _imageUrl;
	
	private string _collection;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnshapeChanging(string value);
    partial void OnshapeChanged();
    partial void OnsizeChanging(string value);
    partial void OnsizeChanged();
    partial void OnimageUrlChanging(string value);
    partial void OnimageUrlChanged();
    partial void OncollectionChanging(string value);
    partial void OncollectionChanged();
    #endregion
	
	public Table_Product()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string code
	{
		get
		{
			return this._code;
		}
		set
		{
			if ((this._code != value))
			{
				this.OncodeChanging(value);
				this.SendPropertyChanging();
				this._code = value;
				this.SendPropertyChanged("code");
				this.OncodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shape", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string shape
	{
		get
		{
			return this._shape;
		}
		set
		{
			if ((this._shape != value))
			{
				this.OnshapeChanging(value);
				this.SendPropertyChanging();
				this._shape = value;
				this.SendPropertyChanged("shape");
				this.OnshapeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_size", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string size
	{
		get
		{
			return this._size;
		}
		set
		{
			if ((this._size != value))
			{
				this.OnsizeChanging(value);
				this.SendPropertyChanging();
				this._size = value;
				this.SendPropertyChanged("size");
				this.OnsizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageUrl", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
	public string imageUrl
	{
		get
		{
			return this._imageUrl;
		}
		set
		{
			if ((this._imageUrl != value))
			{
				this.OnimageUrlChanging(value);
				this.SendPropertyChanging();
				this._imageUrl = value;
				this.SendPropertyChanged("imageUrl");
				this.OnimageUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collection", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string collection
	{
		get
		{
			return this._collection;
		}
		set
		{
			if ((this._collection != value))
			{
				this.OncollectionChanging(value);
				this.SendPropertyChanging();
				this._collection = value;
				this.SendPropertyChanged("collection");
				this.OncollectionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_News")]
public partial class Table_News : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Title;
	
	private string _Body;
	
	private System.DateTime _Date;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    #endregion
	
	public Table_News()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Body
	{
		get
		{
			return this._Body;
		}
		set
		{
			if ((this._Body != value))
			{
				this.OnBodyChanging(value);
				this.SendPropertyChanging();
				this._Body = value;
				this.SendPropertyChanged("Body");
				this.OnBodyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Info")]
public partial class Table_Info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _CompanyName;
	
	private string _Description;
	
	private string _ContactAddress;
	
	private string _ContactRole;
	
	private string _ContactPhone;
	
	private string _ContactMobie;
	
	private string _ContactSkype;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnContactAddressChanging(string value);
    partial void OnContactAddressChanged();
    partial void OnContactRoleChanging(string value);
    partial void OnContactRoleChanged();
    partial void OnContactPhoneChanging(string value);
    partial void OnContactPhoneChanged();
    partial void OnContactMobieChanging(string value);
    partial void OnContactMobieChanged();
    partial void OnContactSkypeChanging(string value);
    partial void OnContactSkypeChanged();
    #endregion
	
	public Table_Info()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string CompanyName
	{
		get
		{
			return this._CompanyName;
		}
		set
		{
			if ((this._CompanyName != value))
			{
				this.OnCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._CompanyName = value;
				this.SendPropertyChanged("CompanyName");
				this.OnCompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactAddress", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string ContactAddress
	{
		get
		{
			return this._ContactAddress;
		}
		set
		{
			if ((this._ContactAddress != value))
			{
				this.OnContactAddressChanging(value);
				this.SendPropertyChanging();
				this._ContactAddress = value;
				this.SendPropertyChanged("ContactAddress");
				this.OnContactAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactRole", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string ContactRole
	{
		get
		{
			return this._ContactRole;
		}
		set
		{
			if ((this._ContactRole != value))
			{
				this.OnContactRoleChanging(value);
				this.SendPropertyChanging();
				this._ContactRole = value;
				this.SendPropertyChanged("ContactRole");
				this.OnContactRoleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPhone", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string ContactPhone
	{
		get
		{
			return this._ContactPhone;
		}
		set
		{
			if ((this._ContactPhone != value))
			{
				this.OnContactPhoneChanging(value);
				this.SendPropertyChanging();
				this._ContactPhone = value;
				this.SendPropertyChanged("ContactPhone");
				this.OnContactPhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMobie", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string ContactMobie
	{
		get
		{
			return this._ContactMobie;
		}
		set
		{
			if ((this._ContactMobie != value))
			{
				this.OnContactMobieChanging(value);
				this.SendPropertyChanging();
				this._ContactMobie = value;
				this.SendPropertyChanged("ContactMobie");
				this.OnContactMobieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactSkype", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string ContactSkype
	{
		get
		{
			return this._ContactSkype;
		}
		set
		{
			if ((this._ContactSkype != value))
			{
				this.OnContactSkypeChanging(value);
				this.SendPropertyChanging();
				this._ContactSkype = value;
				this.SendPropertyChanged("ContactSkype");
				this.OnContactSkypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
